#!/bin/bash
set -e

#DEBHELPER#
if [ "$1" = "configure" ]; then
    systemctl enable proxlb_agent.service
    systemctl restart proxlb_agent.service || true

    # Create the 'plb' user if it does not exist
    if ! id "plba" &>/dev/null; then
        useradd --system --home /var/lib/proxlb_agent --create-home --shell /usr/sbin/nologin --group nogroup plba
        echo "User 'plba' created."
    else
        echo "User 'plba' already exists, skipping creation."
    fi
fi